### ISSUE TITLE
DID id and key are null

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-wallet#73]
I ran the wallet-design branch and created a new identity. The did id and the key were null on the downloaded file.

```json
{
  "did": {
    "id": null,
    "privateKeyBase58": null
  },
  "testnet": true,
  "bitcoinMnemonic": "consider mountain female deal memory adapt slow diet escape ready else rescue",
  "address": "mnbPSGXQHtMu1h3D6EeZ8Aneqs5Ljubnna"
}
```

**Comment by fazo96** [comment]
Fixed in https://github.com/ChluNetwork/chlu-wallet/commit/bc7ca2487dc5db212a84694453c7bf5b228dbdd0
