### ISSUE TITLE
Switch to Material provided CssBaseline

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-wallet#76]
This will allow us to get rid of hand coded margin/padding fixes that @fazo96 has added. Assiging to @fazo96 as he knows where he has to remove the hand coded normalizations from.

**Comment by fazo96** [comment]
Fixed in https://github.com/ChluNetwork/chlu-wallet/commit/241d19dd6aa373f8214244d01459736ab2871a24
