### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuurw** [ChluNetwork/chlu-wallet#98]
Hello, Im a Graphic Designer that likes to contribute to open source projects, I would like to know if you need a logo for you project? I would like to work with you.

If you want just tell me what you want for the logo?

Greetings

**Comment by mcsweenb** [comment]
Nice. Are you offering to design one for free? Do you have a portfolio?

**Comment by zuurw** [comment]
Hello, here are some of my design for open source projects.

Is free the design of the logo, can you tell me if you have something in your mind for your logo?

cheers!

![projects logo](https://user-images.githubusercontent.com/40801473/42339708-ad863e48-8085-11e8-99a9-eef4cc27c40c.png)

**Comment by mcsweenb** [comment]
Thank you so much! Your designs are lovely. You are a very talented designer! No real hard ideas but would love to see what you can come up with. As inspiration, the following might help you:

- We are focused on solving problems in the area of "Ratings & Reviews"
- Our process is a 3 stage process - 1) Pay 2) Review 3) Earn Chlu. 
- We use "decentralized" or "blockchain" technology

Does this help with ideas?

**Comment by zuurw** [comment]
Thanks for your words.

I will start to design today I will used that ideas.

Cheers.

**Comment by zuurw** [comment]
Hello, here is my 2 designs for your logo, see if you understand the concept.

![wallet](https://user-images.githubusercontent.com/40801473/42405478-6532e13c-818e-11e8-87f3-2207704a7b89.png)

**Comment by zuurw** [comment]
Hi @mcsweenb, send me your feedback about the design, did you like it?

**Comment by mcsweenb** [comment]
we totally get the direction you are going in but think that it looks a little too old school for a tech company unfortunately. Perhaps the problem was my specific direction. I REALLY appreciate your effort and we did discuss it with the team.

**Comment by zuurw** [comment]
Hi @mcsweenb 
No problem I can design other logo, can you be more specific in what you want? Do you have something for inspiration?

Cheers!

**Comment by zuurw** [comment]
Hi @mcsweenb, I design this new logo for your project, see if you like this one.
![wallet proposal](https://user-images.githubusercontent.com/40801473/42736391-0c36f22c-885e-11e8-867c-9f8df212c82c.png)

**Comment by mcsweenb** [comment]
Thank you @zuurw !! We definitely prefer this direction. Specifically, we like the fact that the lock motif also has blocks so it does make you think of blockchain, also, we think that the fat outer ring looks a little bit like the C in Chlu. 

I have a suggestion...could we try to maybe simplify it a slight bit? For example, instead of three thicknesses on the outer ring, perhaps we could just have two - the fattest one and the thinnest one? That might make the outer Block look even more like a C. 

Maybe a second version if you try to simplify them all to be like the second smallest circle...the one with the single thick line and the rest of them as blocks. Make sense?

**Comment by zuurw** [comment]
Hi @mcsweenb, I will make changes that you request.

Best Regards!

**Comment by zuurw** [comment]
Hi @mcsweenb,

Hi made the changes like you ask, I think so.

I create other variations of the logo, I start to delete some lines to see how it looks.

here are the results.

![logo proposal version3](https://user-images.githubusercontent.com/40801473/43001570-95e5855c-8c1d-11e8-9525-e5aa0530604c.png)

**Comment by mcsweenb** [comment]
hi @zuurw this is definitely getting to a cool design. We are close! I have some very specific feedback that I think we can do to tweak the designs one final time. I've made a very rough example of what i think could work really well. Simplified to 3 concentric circles. Made each one the exact same, just inverse of each other vertically. Each one is thick like a C (about 2/3's of the circle) plus a block.

<img width="247" alt="screen shot 2018-07-20 at 6 43 28 pm" src="https://user-images.githubusercontent.com/149767/43028271-f1686e38-8c4c-11e8-8e9f-c16b9917a44d.png">

I would love to see an example of this with the text below and maybe also it would be great to get one in white with a transparent background so we can drop it into our wallet.chlu.io page to see how it looks!

Let me know if this makes sense and thanks so much again!
Brian

**Comment by zuurw** [comment]
Hello @mcsweenb I made the changes that you requested and I think they look very good.

Here are the changes, I put also the white versions of the logomark and logotype.

![logo proposal version4](https://user-images.githubusercontent.com/40801473/43040692-5c4e0852-8d42-11e8-9a0d-b83e0652331a.png)

![logomark white](https://user-images.githubusercontent.com/40801473/43040715-ec92e482-8d42-11e8-8d16-0f7b7860368a.png)
![logotype vertical](https://user-images.githubusercontent.com/40801473/43040716-ecc8ce08-8d42-11e8-9ef0-e21c25eb1950.png)

**Comment by zuurw** [comment]
Hi @mcsweenb did you see the changes that I made? does the project team like it?

**Comment by zuurw** [comment]
Hello @mcsweenb, no problem!

Here are the changes that you request, I think it looks really good, see if is this what you want, if you need more changes no problem!

Best Regards!

![logo proposal version5](https://user-images.githubusercontent.com/40801473/43413950-59da87ec-9429-11e8-8bce-857480c60606.png)
![logomark white](https://user-images.githubusercontent.com/40801473/43413961-5e7db292-9429-11e8-9424-52d6b1189eea.png)
![logotype vertical](https://user-images.githubusercontent.com/40801473/43413962-5ea214e8-9429-11e8-8b5c-bc4c1bfbc125.png)

**Comment by mcsweenb** [comment]
@zuurw we love it! We are figuring out how to integrate it to the site! Thanks so much :) We will add you to the Chlu team on github :)

**Comment by zuurw** [comment]
Hi @mcsweenb, Im happy to ear that and that you like the final result, can I submit by PR the files of the logo, I will send you PNG and SVG (you can edit this one) do you want other type of files?
Thank you!

**Comment by JohnWeisz** [comment]
Hey @zuurw,

First I'd like to say that I absolutely love your logo, it's very expressive yet simple at the same time. Thank you very much for your contribution!

I've replicated your logo in SVG through a React component, and @mcsweenb made some further modifications to it. You can check the code at https://github.com/ChluNetwork/chlu-wallet/blob/new-logo-test/src/containers/Layout/ChluLogo.js if interested (or check it out on live at https://wallet.chlu.io/), it also has a cool animation added to it!

**Comment by zuurw** [comment]
Hi how  are you? I upload the Logomark, Logotype vertical and horizontal of chlu in a PR.
I send all the files in svg, png and eps.

If you want I can send you by google drive link.

Do you have other projects like this to contribute with design? I would like to work with you in them.

Best Regards!

Zuur Willem.
